### ISSUE TITLE
Sorry, but i can not run

### ISSUE THREAD

**Issue by KatherineWe** [jefflai108/Attentive-Filtering-Network#3]
For run_feature.sh,  no such file data/*_cqcc_spectrogram/utt2spk, can you help to upload the data directory?
For run.sh, no module named 'adv_kaldi_io'.
For make_spectrogram.sh, line 18: parse_options.sh: No such file or directory.
Can u help to upload these files? Thank u very much!

**Comment by jefflai108** [comment]
hi @KatherineWe 
Sorry for the late reply. I was on vacation. Regarding your questions: 
Are you familiar with Kaldi (https://kaldi-asr.org)? This repo is based on Kaldi. The "parse_options.sh" error arose due to incorrect setup of your Kaldi directory (check path.sh file and make sure your Kaldi path is correct). As for utt2spk, you may have to generate it yourself (it is simple!). In Kaldi, the data directory has three files: feats.scp, utt2spk, wav.scp. You'll need wav.scp and utt2spk for Kaldi to extract log mel spec features. 

An example of utt2spk would be like this (for this dataset):
M0019-E_1000014 M0019
M0019-E_1000028 M0019
M0019-E_1000036 M0019
M0019-E_1000050 M0019
where M0019-E_1000050 is the utterance ID and M0019 is the speaker ID. You can easily generate this in python or bash. 

Let me know if you have further trouble :)
