### ISSUE TITLE
can't not run run_feature.sh

### ISSUE THREAD

**Issue by LeoMax-Xiong** [jefflai108/Attentive-Filtering-Network#6]
there are several questions when I run the project
1. when I run run_feature.sh according to the readme,  it occurs the errors about no train_cqcc_spectrogram；
2. should I change the stage in run_feature.sh, change -4 to 4 in line 53 in run_feature.sh;
3. i cannot generate cqcc feature using kaldi

**Comment by jefflai108** [comment]
hi @Honei 

1. you have to generate futures by run_feature.sh 
2. run the script stage by stage. This is by design, that after each stage, intermediate results are stored and remaining stages should only depends on these results.
3. Yes, you'll need the official MATLAB script. you can find them easily online.
